Library yang akan digunakan

In [16]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score

Load Dataset

In [17]:
stunting_dataset = pd.read_csv('Dataset_Skripsi.csv')

In [18]:
stunting_dataset.head()

Usia Jenis_Kelamin  BB_Lahir  TB_Lahir  BB_Sekarang  TB_Sekarang Stunting
0     0     Laki-laki      2.90        49         2.90         49.0       No
1     0     Laki-laki      2.40        42         3.30         52.0       No
2     0     Perempuan      2.70        48         2.70         48.0       No
3     1     Laki-laki      3.58        50         4.31         54.0       No
4     1     Perempuan      2.25        48         4.00         51.0       No

In [19]:
stunting_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1784 entries, 0 to 1783
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Usia           1784 non-null   int64  
 1   Jenis_Kelamin  1784 non-null   object 
 2   BB_Lahir       1784 non-null   float64
 3   TB_Lahir       1784 non-null   int64  
 4   BB_Sekarang    1784 non-null   float64
 5   TB_Sekarang    1784 non-null   float64
 6   Stunting       1784 non-null   object 
dtypes: float64(3), int64(2), object(2)
memory usage: 97.7+ KB


In [20]:
from IPython.display import display
display(stunting_dataset)

Usia Jenis_Kelamin  BB_Lahir  TB_Lahir  BB_Sekarang  TB_Sekarang  \
0        0     Laki-laki      2.90        49         2.90         49.0   
1        0     Laki-laki      2.40        42         3.30         52.0   
2        0     Perempuan      2.70        48         2.70         48.0   
3        1     Laki-laki      3.58        50         4.31         54.0   
4        1     Perempuan      2.25        48         4.00         51.0   
...    ...           ...       ...       ...          ...          ...   
1779    60     Perempuan      3.30        48        18.10        114.2   
1780    60     Laki-laki      3.00        48        13.60         96.5   
1781    60     Laki-laki      3.00        48        13.90         96.5   
1782    60     Perempuan      3.50        49        15.30         95.2   
1783    60     Laki-laki      3.00        49        13.00         92.2   

     Stunting  
0          No  
1          No  
2          No  
3          No  
4          No  
...       ...  
1779       No  
1780      Yes  
1781      Yes  
1782      Yes  
1783      Yes  

[1784 rows x 7 columns]

In [21]:
stunting_dataset.shape 

(1784, 7)

In [22]:
duplikat_kolom = stunting_dataset[
    stunting_dataset.duplicated(
        subset=["Usia", "Jenis_Kelamin", "BB_Lahir", "TB_Lahir",
                "BB_Sekarang", "TB_Sekarang", "Stunting"]
    )
]

if duplikat_kolom.empty:
    print("Tidak ada data duplikat berdasarkan kolom yang dipilih.")
else:
    print("Data duplikat ditemukan:")
    print(duplikat_kolom)


Tidak ada data duplikat berdasarkan kolom yang dipilih.


Pengecekan Missing Value

In [23]:
stunting_dataset.isnull().sum()

Usia             0
Jenis_Kelamin    0
BB_Lahir         0
TB_Lahir         0
BB_Sekarang      0
TB_Sekarang      0
Stunting         0
dtype: int64

Label Encoding

In [24]:
stunting_dataset['Jenis_Kelamin'] = stunting_dataset['Jenis_Kelamin'].replace({'Laki-laki':1,'Perempuan':0})
stunting_dataset['Stunting'] = stunting_dataset['Stunting'].replace({'No':0,'Yes':1})

In [25]:
# memisahkan data dan label
X = stunting_dataset.drop (columns='Stunting', axis=1)
Y = stunting_dataset['Stunting'] 

In [26]:
print(X) 

      Usia  Jenis_Kelamin  BB_Lahir  TB_Lahir  BB_Sekarang  TB_Sekarang
0        0              1      2.90        49         2.90         49.0
1        0              1      2.40        42         3.30         52.0
2        0              0      2.70        48         2.70         48.0
3        1              1      3.58        50         4.31         54.0
4        1              0      2.25        48         4.00         51.0
...    ...            ...       ...       ...          ...          ...
1779    60              0      3.30        48        18.10        114.2
1780    60              1      3.00        48        13.60         96.5
1781    60              1      3.00        48        13.90         96.5
1782    60              0      3.50        49        15.30         95.2
1783    60              1      3.00        49        13.00         92.2

[1784 rows x 6 columns]


In [27]:
print(Y)

0       0
1       0
2       0
3       0
4       0
       ..
1779    0
1780    1
1781    1
1782    1
1783    1
Name: Stunting, Length: 1784, dtype: int64


Standarisasi Data

In [28]:
scaler = StandardScaler()
scaler.fit(X)
standarized_data = scaler.transform(X) 
X = standarized_data
Y = stunting_dataset['Stunting'] 
print(X)
print(Y)

[[-2.04940659  0.88745431 -0.36839945  0.62202418 -2.72564926 -2.97862502]
 [-2.04940659  0.88745431 -1.42936324 -2.63083929 -2.5956717  -2.73117569]
 [-2.04940659 -1.12681858 -0.79278497  0.1573294  -2.79063805 -3.06110812]
 ...
 [ 1.76496773  0.88745431 -0.1562067   0.1573294   0.84873384  0.93932263]
 [ 1.76496773 -1.12681858  0.90475709  0.62202418  1.30365533  0.83209459]
 [ 1.76496773  0.88745431 -0.1562067   0.62202418  0.55628432  0.58464527]]
0       0
1       0
2       0
3       0
4       0
       ..
1779    0
1780    1
1781    1
1782    1
1783    1
Name: Stunting, Length: 1784, dtype: int64


Memisahkan Data Training dan Data Testing

In [29]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size= 0.2, stratify=Y, random_state=42)
print(X.shape, X_train.shape, X_test.shape)

(1784, 6) (1427, 6) (357, 6)


In [30]:
from sklearn.model_selection import GridSearchCV

# Inisialisasi model SVM
svm_model = SVC(probability=True, random_state=42)

# Parameter grid untuk dicoba
param_grid = {
    'C': [0.1, 1, 10, 100],             # regularisasi
    'kernel': ['linear', 'poly', 'rbf', 'sigmoid'],  # jenis kernel
}

grid_search = GridSearchCV(
    estimator=svm_model,
    param_grid=param_grid,
    cv=5,            # 5-fold cross validation
    n_jobs=-1,       # pakai semua core CPU
    verbose=2,       # tampilkan progres
    scoring='accuracy'  # metrik evaluasi
)

# Jalankan pencarian grid
grid_search.fit(X_train, Y_train)

print("Best Parameters:", grid_search.best_params_)
print("Best Accuracy:", grid_search.best_score_)


Fitting 5 folds for each of 16 candidates, totalling 80 fits
Best Parameters: {'C': 100, 'kernel': 'rbf'}
Best Accuracy: 0.9362384983437615


Membuat data latih menggunakan algoritma Random Forest


In [31]:
model_svm = SVC(C=10, kernel='rbf')
model_svm.fit(X_train, Y_train)


SVC(C=10)

Membuat model evaluasi untuk mengukur tingkat akurasi

In [32]:
sv = model_svm.predict(X_train)
training_data_accuracy = accuracy_score(sv,Y_train)
print('Akurasi data training adalah =', training_data_accuracy)


sv = model_svm.predict(X_test)
test_data_accuracy = accuracy_score(sv,Y_test)
print('Akurasi data testing adalah =', test_data_accuracy)

Akurasi data training adalah = 0.956552207428171
Akurasi data testing adalah = 0.9243697478991597


In [33]:
from sklearn.metrics import confusion_matrix

# Prediksi data uji
y_pred = model_svm.predict(X_test)

# Hitung confusion matrix
cm = confusion_matrix(Y_test, y_pred)
TN, FP, FN, TP = cm.ravel()

# Hitung metrik
sensitivitas = TP / (TP + FN)  
spesifisitas = TN / (TN + FP)  

print("Confusion Matrix:\n", cm)
print(f"Sensitivitas (Recall): {sensitivitas}")
print(f"Spesifisitas: {spesifisitas}")


Confusion Matrix:
 [[166  20]
 [  7 164]]
Sensitivitas (Recall): 0.9590643274853801
Spesifisitas: 0.8924731182795699


Membuat model deteksi

In [34]:
input_data = (7,1,3.8,49,28,72.2)

input_data_as_numpy_array = np.array(input_data)

input_data_reshape = input_data_as_numpy_array.reshape(1,-1)

std_data = scaler.transform(input_data_reshape)
print(std_data)

prediction = model_svm.predict(std_data)
print(prediction)

if (prediction[0] == 0):
    print('Anak tidak berisiko stunting')
else :
    print('Anak berisiko stunting') 

[[-1.60439625  0.88745431  1.54133535  0.62202418  5.4304431  -1.0650169 ]]
[0]
Anak tidak berisiko stunting


c:\Users\aritr\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


Simpan model

In [ ]:
#import pickle
#pickle.dump(model_svm, open('stunting.sav', 'wb'))
#pickle.dump(scaler, open('scaler.sav', 'wb'))